DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    USERNAME VARCHAR(255) NULL,
    PASSWORD VARCHAR(255) NULL,
    ROLE VARCHAR(255) NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ADMIN;
CREATE TABLE ADMIN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    NAME VARCHAR(255) NULL,
    REGISTERED_USER_ID BIGINT NULL,
    PRIMARY KEY (ID),
    UNIQUE (REGISTERED_USER_ID),
    FOREIGN KEY (REGISTERED_USER_ID) REFERENCES USER(ID)
);

DROP TABLE IF EXISTS COLLEGE;
CREATE TABLE COLLEGE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    NAME VARCHAR(255) NULL,
    CODE VARCHAR(255) NULL,
    ADDRESS VARCHAR(255) NULL,
    PRINCIPAL_ID BIGINT NULL,
    ADMIN_ID BIGINT NULL,
    PRIMARY KEY (ID),
    UNIQUE (PRINCIPAL_ID),
    FOREIGN KEY (PRINCIPAL_ID) REFERENCES AUTHORITY(ID),
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID)
);

DROP TABLE IF EXISTS AUTHORITY;
CREATE TABLE AUTHORITY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    EMP_ID VARCHAR(255) NULL,
    FIRST_NAME VARCHAR(255) NULL,
    LAST_NAME VARCHAR(255) NULL,
    DESIGNATION VARCHAR(255) NULL,
    DEPARTMENT_ID BIGINT NULL,
    REGISTERED_USER_ID BIGINT NULL,
    PRIMARY KEY (ID),
    UNIQUE (REGISTERED_USER_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    FOREIGN KEY (REGISTERED_USER_ID) REFERENCES USER(ID)
);

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    NAME VARCHAR(255) NULL,
    HOD_ID BIGINT NULL,
    COLLEGE_ID BIGINT NULL,
    PRIMARY KEY (ID),
    UNIQUE (HOD_ID),
    FOREIGN KEY (HOD_ID) REFERENCES AUTHORITY(ID),
    FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(ID)
);

DROP TABLE IF EXISTS BATCH_DETAILS;
CREATE TABLE BATCH_DETAILS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    START_YEAR INT NULL,
    END_YEAR INT NULL,
    DEPARTMENT_ID BIGINT NULL,
    FACULTY_ID BIGINT NULL,
    STATUS ENUM('ACTIVE','INACTIVE') NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    FOREIGN KEY (FACULTY_ID) REFERENCES AUTHORITY(ID)
);

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL DEFAULT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL,
    FIRST_NAME VARCHAR(255) DEFAULT NULL,
    LAST_NAME VARCHAR(255) DEFAULT NULL,
    ROLL_NO VARCHAR(255) DEFAULT NULL,
    BATCH_ID BIGINT DEFAULT NULL,
    REGISTERED_USER_ID BIGINT DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK3HG7LRIRODPB6JGGVNHKTJ18R (REGISTERED_USER_ID),
    KEY FK67HAMDOBIO3FA76XS3YVGO9YO (BATCH_ID),
    CONSTRAINT FK67HAMDOBIO3FA76XS3YVGO9YO FOREIGN KEY (BATCH_ID) REFERENCES BATCH_DETAILS (ID),
    CONSTRAINT FKEEOXJ48HDH02N1J461568YEDN FOREIGN KEY (REGISTERED_USER_ID) REFERENCES USER (ID)
);

DROP TABLE IF EXISTS REQUEST_DETAILS;
CREATE TABLE REQUEST_DETAILS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL DEFAULT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL,
    REQUEST_TITLE VARCHAR(255) DEFAULT NULL,
    REQUEST_BODY VARCHAR(255) DEFAULT NULL,
    STATUS ENUM(
        'APPROVED_BY_FACULTY',
        'APPROVED_BY_HOD',
        'APPROVED_BY_PRINCIPAL',
        'MOVED_TO_FACULTY',
        'MOVED_TO_HOD',
        'MOVED_TO_PRINCIPAL',
        'REJECTED_BY_FACULTY',
        'REJECTED_BY_HOD',
        'REJECTED_BY_PRINCIPAL'
    ) DEFAULT NULL,
    STUDENT_ID BIGINT DEFAULT NULL,
    PRIMARY KEY (ID),
    KEY FKJ6MFX1KFPELKVF1KD6M4FPAM7 (STUDENT_ID),
    CONSTRAINT FKJ6MFX1KFPELKVF1KD6M4FPAM7 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID)
);

DROP TABLE IF EXISTS APPROVAL_INFO;
CREATE TABLE APPROVAL_INFO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL DEFAULT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL,
    REQUEST_ID BIGINT DEFAULT NULL,
    NEED_HOD_SIGN BIT(1) DEFAULT NULL,
    NEED_PRINCIPAL_SIGN BIT(1) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UKO9MTGQ8Q26QRBDD14G18GIU1K (REQUEST_ID),
    CONSTRAINT FKDRHWP7EPIGTC8OY325QX3TX24 
        FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_DETAILS (ID)
);

DROP TABLE IF EXISTS CERTIFICATE_INFO;
CREATE TABLE CERTIFICATE_INFO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP NULL DEFAULT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL,
    REQUEST_ID BIGINT DEFAULT NULL,
    LINK VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK2AT6VGMIG62D97Q9WRJ2G3T1M (REQUEST_ID),
    CONSTRAINT FKDW3DMRGPIWTMJUKBQ3W6498II 
        FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST_DETAILS (ID)
);

-- =========================================================
-- ADMIN SETUP
-- =========================================================
INSERT INTO USER VALUES (1, NOW(), NOW(), "Admin", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "ADMIN");
INSERT INTO ADMIN VALUES (1, NOW(), NOW(), "Admin", 1);

-- =========================================================
-- COLLEGE SETUP
-- =========================================================
INSERT INTO COLLEGE VALUES (1, NOW(), NOW(), "Government College of Technology", "2005", "COIMBATORE", 1, 1);
INSERT INTO COLLEGE VALUES (2, NOW(), NOW(), "Coimbatore Institute of Technology", "7176", "COIMBATORE", 2, 1);

-- =========================================================
-- PRINCIPAL SETUP
-- =========================================================
INSERT INTO AUTHORITY VALUES (1, NOW(), NOW(), 1001, "Thamarai", "Kannan", "PRINCIPAL", NULL, 2);
INSERT INTO AUTHORITY VALUES (2, NOW(), NOW(), 1002, "Hari", "Haran", "PRINCIPAL", NULL, 3);

INSERT INTO USER VALUES (2, NOW(), NOW(), "GCT_Principal", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "PRINCIPAL");
INSERT INTO USER VALUES (3, NOW(), NOW(), "CIT_Principal", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "PRINCIPAL");

-- =========================================================
-- DEPARTMENT SETUP
-- =========================================================
INSERT INTO DEPARTMENT VALUES (1, NOW(), NOW(), "CSE", 3, 1);
INSERT INTO DEPARTMENT VALUES (2, NOW(), NOW(), "IT", 4, 1);
INSERT INTO DEPARTMENT VALUES (3, NOW(), NOW(), "AI&ML", 5, 1);
INSERT INTO DEPARTMENT VALUES (4, NOW(), NOW(), "EEE", 6, 1);
INSERT INTO DEPARTMENT VALUES (5, NOW(), NOW(), "ECE", 7, 1);

INSERT INTO DEPARTMENT VALUES (6, NOW(), NOW(), "CSE", 8, 2);
INSERT INTO DEPARTMENT VALUES (7, NOW(), NOW(), "IT", 9, 2);
INSERT INTO DEPARTMENT VALUES (8, NOW(), NOW(), "AI&ML", 10, 2);
INSERT INTO DEPARTMENT VALUES (9, NOW(), NOW(), "EEE", 11, 2);
INSERT INTO DEPARTMENT VALUES (10, NOW(), NOW(), "ECE", 12, 2);

-- =========================================================
-- HOD SETUP
-- =========================================================
INSERT INTO AUTHORITY VALUES (3, NOW(), NOW(), 1003, "Prabhakaran", "Chakravarthi", "HOD", 1, 4);
INSERT INTO AUTHORITY VALUES (4, NOW(), NOW(), 1004, "Arun", "Kumar", "HOD", 2, 5);
INSERT INTO AUTHORITY VALUES (5, NOW(), NOW(), 1005, "Suresh", "Babu", "HOD", 3, 6);
INSERT INTO AUTHORITY VALUES (6, NOW(), NOW(), 1006, "Vignesh", "Rajan", "HOD", 4, 7);
INSERT INTO AUTHORITY VALUES (7, NOW(), NOW(), 1007, "Karthik", "Narayanan", "HOD", 5, 8);

INSERT INTO AUTHORITY VALUES (8, NOW(), NOW(), 1008, "Dinesh", "Krishnan", "HOD", 6, 9);
INSERT INTO AUTHORITY VALUES (9, NOW(), NOW(), 1009, "Ramesh", "Subramanian", "HOD", 7, 10);
INSERT INTO AUTHORITY VALUES (10, NOW(), NOW(), 1010, "Ganesh", "Murugan", "HOD", 8, 11);
INSERT INTO AUTHORITY VALUES (11, NOW(), NOW(), 1011, "Saravanan", "Manohar", "HOD", 9, 12);
INSERT INTO AUTHORITY VALUES (12, NOW(), NOW(), 1012, "Vijay", "Karthikeyan", "HOD", 10, 13);

-- =========================================================
-- HOD USER ACCOUNTS
-- =========================================================
INSERT INTO USER VALUES (4, NOW(), NOW(), "GCT_CSE_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (5, NOW(), NOW(), "GCT_IT_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (6, NOW(), NOW(), "GCT_AIML_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (7, NOW(), NOW(), "GCT_EEE_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (8, NOW(), NOW(), "GCT_ECE_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");

INSERT INTO USER VALUES (9, NOW(), NOW(), "CIT_CSE_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (10, NOW(), NOW(), "CIT_IT_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (11, NOW(), NOW(), "CIT_AIML_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (12, NOW(), NOW(), "CIT_EEE_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");
INSERT INTO USER VALUES (13, NOW(), NOW(), "CIT_ECE_Hod", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "HOD");

-- =========================================================
-- FACULTY SETUP
-- =========================================================
INSERT INTO AUTHORITY VALUES (14, NOW(), NOW(), 1003, "Aravind", "Srinivasan", "FACULTY", 1, 14);
INSERT INTO AUTHORITY VALUES (15, NOW(), NOW(), 1004, "Manikandan", "Ravi", "FACULTY", 1, 15);
INSERT INTO AUTHORITY VALUES (16, NOW(), NOW(), 1005, "Senthil", "Kumar", "FACULTY", 1, 16);
INSERT INTO AUTHORITY VALUES (17, NOW(), NOW(), 1006, "Harish", "Balaji", "FACULTY", 1, 17);
INSERT INTO AUTHORITY VALUES (18, NOW(), NOW(), 1007, "Pradeep", "Natarajan", "FACULTY", 1, 18);

INSERT INTO AUTHORITY VALUES (19, NOW(), NOW(), 1008, "Lokesh", "Venkatesh", "FACULTY", 2, 19);
INSERT INTO AUTHORITY VALUES (20, NOW(), NOW(), 1009, "Madhan", "Rajasekar", "FACULTY", 2, 20);
INSERT INTO AUTHORITY VALUES (21, NOW(), NOW(), 1010, "Raghav", "Subramani", "FACULTY", 2, 21);
INSERT INTO AUTHORITY VALUES (22, NOW(), NOW(), 1011, "Sathish", "Karthik", "FACULTY", 2, 22);
INSERT INTO AUTHORITY VALUES (23, NOW(), NOW(), 1012, "Vimal", "Prakash", "FACULTY", 2, 23);

INSERT INTO AUTHORITY VALUES (24, NOW(), NOW(), 1013, "Deepak", "Arun", "FACULTY", 6, 24);
INSERT INTO AUTHORITY VALUES (25, NOW(), NOW(), 1014, "Surya", "Narayanan", "FACULTY", 6, 25);
INSERT INTO AUTHORITY VALUES (26, NOW(), NOW(), 1015, "Ajith", "Kumar", "FACULTY", 6, 26);
INSERT INTO AUTHORITY VALUES (27, NOW(), NOW(), 1016, "Kiran", "Raj", "FACULTY", 6, 27);
INSERT INTO AUTHORITY VALUES (28, NOW(), NOW(), 1017, "Vishal", "Anand", "FACULTY", 6, 28);

INSERT INTO AUTHORITY VALUES (29, NOW(), NOW(), 1018, "Naveen", "Raghavan", "FACULTY", 7, 29);
INSERT INTO AUTHORITY VALUES (30, NOW(), NOW(), 1019, "Gokul", "Krishnan", "FACULTY", 7, 30);
INSERT INTO AUTHORITY VALUES (31, NOW(), NOW(), 1020, "Karthikeyan", "Siva", "FACULTY", 7, 31);
INSERT INTO AUTHORITY VALUES (32, NOW(), NOW(), 1021, "Pravin", "Mohan", "FACULTY", 7, 32);
INSERT INTO AUTHORITY VALUES (33, NOW(), NOW(), 1022, "Ashwin", "Ramesh", "FACULTY", 7, 33);


-- =========================================================
-- FACULTY's USER SETUP
-- =========================================================
INSERT INTO USER VALUES (14, NOW(), NOW(), "GCT_CSE_Faculty1", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (15, NOW(), NOW(), "GCT_CSE_Faculty2", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (16, NOW(), NOW(), "GCT_CSE_Faculty3", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (17, NOW(), NOW(), "GCT_CSE_Faculty4", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (18, NOW(), NOW(), "GCT_CSE_Faculty5", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");

INSERT INTO USER VALUES (19, NOW(), NOW(), "GCT_IT_Faculty1", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (20, NOW(), NOW(), "GCT_IT_Faculty2", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (21, NOW(), NOW(), "GCT_IT_Faculty3", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (22, NOW(), NOW(), "GCT_IT_Faculty4", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (23, NOW(), NOW(), "GCT_IT_Faculty5", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");

INSERT INTO USER VALUES (24, NOW(), NOW(), "CIT_CSE_Faculty1", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (25, NOW(), NOW(), "CIT_CSE_Faculty2", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (26, NOW(), NOW(), "CIT_CSE_Faculty3", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (27, NOW(), NOW(), "CIT_CSE_Faculty4", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (28, NOW(), NOW(), "CIT_CSE_Faculty5", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");

INSERT INTO USER VALUES (29, NOW(), NOW(), "CIT_IT_Faculty1", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (30, NOW(), NOW(), "CIT_IT_Faculty2", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (31, NOW(), NOW(), "CIT_IT_Faculty3", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (32, NOW(), NOW(), "CIT_IT_Faculty4", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");
INSERT INTO USER VALUES (33, NOW(), NOW(), "CIT_IT_Faculty5", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "FACULTY");

-- =========================================================
-- BATCH DETAILS SETUP
-- =========================================================
INSERT INTO BATCH_DETAILS VALUES (1, NOW(), NOW(), 2020, 2023, 1, 14, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (2, NOW(), NOW(), 2021, 2024, 1, 15, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (3, NOW(), NOW(), 2022, 2025, 1, 16, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (4, NOW(), NOW(), 2023, 2026, 1, 17, 'ACTIVE');

INSERT INTO BATCH_DETAILS VALUES (5, NOW(), NOW(), 2020, 2023, 2, 19, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (6, NOW(), NOW(), 2021, 2024, 2, 20, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (7, NOW(), NOW(), 2022, 2025, 2, 21, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (8, NOW(), NOW(), 2023, 2026, 2, 22, 'ACTIVE');

INSERT INTO BATCH_DETAILS VALUES (9, NOW(), NOW(), 2020, 2023, 6, 24, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (10, NOW(), NOW(), 2021, 2024, 6, 25, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (11, NOW(), NOW(), 2022, 2025, 6, 26, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (12, NOW(), NOW(), 2023, 2026, 6, 27, 'ACTIVE');

INSERT INTO BATCH_DETAILS VALUES (13, NOW(), NOW(), 2020, 2023, 7, 29, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (14, NOW(), NOW(), 2021, 2024, 7, 30, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (15, NOW(), NOW(), 2022, 2025, 7, 31, 'ACTIVE');
INSERT INTO BATCH_DETAILS VALUES (16, NOW(), NOW(), 2023, 2026, 7, 32, 'ACTIVE');

-- =========================================================
-- STUDENT SETUP
-- =========================================================
INSERT INTO STUDENT VALUES (1, NOW(), NOW(), "Pavithran", "Ganesan", "1917L10", 1, 34);
INSERT INTO STUDENT VALUES (2, NOW(), NOW(), "Arun", "Kumar", "1917L11", 1, 35);

INSERT INTO STUDENT VALUES (3, NOW(), NOW(), "Suresh", "Babu", "1917L12", 2, 36);
INSERT INTO STUDENT VALUES (4, NOW(), NOW(), "Vignesh", "Rajan", "1917L13", 2, 37);

INSERT INTO STUDENT VALUES (5, NOW(), NOW(), "Karthik", "Narayanan", "1917L14", 3, 38);
INSERT INTO STUDENT VALUES (6, NOW(), NOW(), "Dinesh", "Krishnan", "1917L15", 3, 39);

INSERT INTO STUDENT VALUES (7, NOW(), NOW(), "Ramesh", "Subramanian", "1917L16", 4, 40);
INSERT INTO STUDENT VALUES (8, NOW(), NOW(), "Ganesh", "Murugan", "1917L17", 4, 41);

INSERT INTO STUDENT VALUES (9, NOW(), NOW(), "Saravanan", "Manohar", "1917L18", 5, 42);
INSERT INTO STUDENT VALUES (10, NOW(), NOW(), "Vijay", "Karthikeyan", "1917L19", 5, 43);

INSERT INTO STUDENT VALUES (11, NOW(), NOW(), "Pradeep", "Natarajan", "1917L20", 6, 44);
INSERT INTO STUDENT VALUES (12, NOW(), NOW(), "Lokesh", "Venkatesh", "1917L21", 6, 45);

INSERT INTO STUDENT VALUES (13, NOW(), NOW(), "Madhan", "Rajasekar", "1917L22", 7, 46);
INSERT INTO STUDENT VALUES (14, NOW(), NOW(), "Raghav", "Subramani", "1917L23", 7, 47);

INSERT INTO STUDENT VALUES (15, NOW(), NOW(), "Sathish", "Karthik", "1917L24", 8, 48);
INSERT INTO STUDENT VALUES (16, NOW(), NOW(), "Vimal", "Prakash", "1917L25", 8, 49);

INSERT INTO STUDENT VALUES (17, NOW(), NOW(), "Deepak", "Arun", "1917L26", 9, 50);
INSERT INTO STUDENT VALUES (18, NOW(), NOW(), "Surya", "Narayanan", "1917L27", 9, 51);

INSERT INTO STUDENT VALUES (19, NOW(), NOW(), "Ajith", "Kumar", "1917L28", 10, 52);
INSERT INTO STUDENT VALUES (20, NOW(), NOW(), "Kiran", "Raj", "1917L29", 10, 53);

INSERT INTO STUDENT VALUES (21, NOW(), NOW(), "Vishal", "Anand", "1917L30", 11, 54);
INSERT INTO STUDENT VALUES (22, NOW(), NOW(), "Naveen", "Raghavan", "1917L31", 11, 55);

INSERT INTO STUDENT VALUES (23, NOW(), NOW(), "Gokul", "Krishnan", "1917L32", 12, 56);
INSERT INTO STUDENT VALUES (24, NOW(), NOW(), "Karthikeyan", "Siva", "1917L33", 12, 57);

INSERT INTO STUDENT VALUES (25, NOW(), NOW(), "Pravin", "Mohan", "1917L34", 13, 58);
INSERT INTO STUDENT VALUES (26, NOW(), NOW(), "Ashwin", "Ramesh", "1917L35", 13, 59);

INSERT INTO STUDENT VALUES (27, NOW(), NOW(), "Aravind", "Srinivasan", "1917L36", 14, 60);
INSERT INTO STUDENT VALUES (28, NOW(), NOW(), "Manikandan", "Ravi", "1917L37", 14, 61);

INSERT INTO STUDENT VALUES (29, NOW(), NOW(), "Senthil", "Kumar", "1917L38", 15, 62);
INSERT INTO STUDENT VALUES (30, NOW(), NOW(), "Harish", "Balaji", "1917L39", 15, 63);

INSERT INTO STUDENT VALUES (31, NOW(), NOW(), "Pradeep", "Natarajan", "1917L40", 16, 64);
INSERT INTO STUDENT VALUES (32, NOW(), NOW(), "Lokesh", "Venkatesh", "1917L41", 16, 65);

-- =========================================================
-- STUDENT USER ACCOUNTS
-- =========================================================
INSERT INTO USER VALUES (34, NOW(), NOW(), "Student1", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (35, NOW(), NOW(), "Student2", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (36, NOW(), NOW(), "Student3", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (37, NOW(), NOW(), "Student4", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (38, NOW(), NOW(), "Student5", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (39, NOW(), NOW(), "Student6", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (40, NOW(), NOW(), "Student7", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (41, NOW(), NOW(), "Student8", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (42, NOW(), NOW(), "Student9", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (43, NOW(), NOW(), "Student10", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (44, NOW(), NOW(), "Student11", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (45, NOW(), NOW(), "Student12", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (46, NOW(), NOW(), "Student13", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (47, NOW(), NOW(), "Student14", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (48, NOW(), NOW(), "Student15", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (49, NOW(), NOW(), "Student16", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (50, NOW(), NOW(), "Student17", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (51, NOW(), NOW(), "Student18", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (52, NOW(), NOW(), "Student19", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (53, NOW(), NOW(), "Student20", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (54, NOW(), NOW(), "Student21", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (55, NOW(), NOW(), "Student22", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (56, NOW(), NOW(), "Student23", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (57, NOW(), NOW(), "Student24", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (58, NOW(), NOW(), "Student25", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (59, NOW(), NOW(), "Student26", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (60, NOW(), NOW(), "Student27", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (61, NOW(), NOW(), "Student28", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (62, NOW(), NOW(), "Student29", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (63, NOW(), NOW(), "Student30", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (64, NOW(), NOW(), "Student31", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");
INSERT INTO USER VALUES (65, NOW(), NOW(), "Student32", "$2a$10$yY0kP8bCWw0j/T.OO.oMAuMjQsNsTLCI.GpKe84bnKnkopL09ORLC", "STUDENT");


-- =========================================================
-- REQUEST FORM SETUP
-- =========================================================
-- Sample requests created by student 1
-- Each request represents a different workflow status
INSERT INTO REQUEST_DETAILS VALUES (1, NOW(), NOW(), "OD Form", "Request for on duty due to symposium", "MOVED_TO_FACULTY", 1);
INSERT INTO REQUEST_DETAILS VALUES (2, NOW(), NOW(), "Leave Request", "Medical leave for two days", "APPROVED_BY_FACULTY", 1);
INSERT INTO REQUEST_DETAILS VALUES (3, NOW(), NOW(), "Internship Permission", "Permission to attend internship program", "APPROVED_BY_HOD", 1);
INSERT INTO REQUEST_DETAILS VALUES (4, NOW(), NOW(), "Project Submission Delay", "Requesting extension for project submission", "APPROVED_BY_PRINCIPAL", 1);
INSERT INTO REQUEST_DETAILS VALUES (5, NOW(), NOW(), "Industrial Visit", "Request for attending industrial visit", "MOVED_TO_HOD", 1);
INSERT INTO REQUEST_DETAILS VALUES (6, NOW(), NOW(), "Conference Participation", "Request to attend technical conference", "MOVED_TO_PRINCIPAL", 1);
INSERT INTO REQUEST_DETAILS VALUES (7, NOW(), NOW(), "Leave Application", "Personal leave request", "REJECTED_BY_FACULTY", 1);
INSERT INTO REQUEST_DETAILS VALUES (8, NOW(), NOW(), "Workshop Permission", "Permission to attend external workshop", "REJECTED_BY_HOD", 1);
INSERT INTO REQUEST_DETAILS VALUES (9, NOW(), NOW(), "Bonafide Certificate", "Request for bonafide certificate for bank", "REJECTED_BY_PRINCIPAL", 1);
INSERT INTO REQUEST_DETAILS VALUES (10, NOW(), NOW(), "OD Form - Tech Fest", "Requesting OD for participating in technical fest", "MOVED_TO_FACULTY", 2);
INSERT INTO REQUEST_DETAILS VALUES (11, NOW(), NOW(), "Medical Leave", "Request for medical leave due to fever", "APPROVED_BY_FACULTY", 2);
INSERT INTO REQUEST_DETAILS VALUES (12, NOW(), NOW(), "Internship Approval", "Permission required to attend internship", "APPROVED_BY_HOD", 2);
INSERT INTO REQUEST_DETAILS VALUES (13, NOW(), NOW(), "Project Extension", "Requesting extension for final year project", "APPROVED_BY_PRINCIPAL", 2);
INSERT INTO REQUEST_DETAILS VALUES (14, NOW(), NOW(), "Industrial Visit Request", "Permission to attend industrial visit", "MOVED_TO_HOD", 2);
INSERT INTO REQUEST_DETAILS VALUES (15, NOW(), NOW(), "Conference Request", "Request to attend national conference", "MOVED_TO_PRINCIPAL", 2);
INSERT INTO REQUEST_DETAILS VALUES (16, NOW(), NOW(), "Personal Leave", "Requesting leave for family function", "REJECTED_BY_FACULTY", 2);
INSERT INTO REQUEST_DETAILS VALUES (17, NOW(), NOW(), "Workshop Request", "Request for attending external workshop", "REJECTED_BY_HOD", 2);
INSERT INTO REQUEST_DETAILS VALUES (18, NOW(), NOW(), "Bonafide Request", "Request for bonafide certificate for scholarship", "REJECTED_BY_PRINCIPAL", 2);

-- =========================================================
-- APPROVAL INFO SETUP
-- =========================================================
-- Determines whether HOD or Principal signature is required
INSERT INTO APPROVAL_INFO VALUES (10, NOW(), NOW(), 10, 0, 0);
INSERT INTO APPROVAL_INFO VALUES (11, NOW(), NOW(), 11, 0, 0);
INSERT INTO APPROVAL_INFO VALUES (12, NOW(), NOW(), 12, 1, 0);
INSERT INTO APPROVAL_INFO VALUES (13, NOW(), NOW(), 13, 1, 1);
INSERT INTO APPROVAL_INFO VALUES (14, NOW(), NOW(), 14, 1, 0);
INSERT INTO APPROVAL_INFO VALUES (15, NOW(), NOW(), 15, 1, 1);
INSERT INTO APPROVAL_INFO VALUES (16, NOW(), NOW(), 16, 0, 0);
INSERT INTO APPROVAL_INFO VALUES (17, NOW(), NOW(), 17, 1, 0);
INSERT INTO APPROVAL_INFO VALUES (18, NOW(), NOW(), 18, 1, 1);
INSERT INTO APPROVAL_INFO VALUES (1, NOW(), NOW(), 1, 0, 0);
INSERT INTO APPROVAL_INFO VALUES (2, NOW(), NOW(), 2, 0, 0);
INSERT INTO APPROVAL_INFO VALUES (3, NOW(), NOW(), 3, 1, 0);
INSERT INTO APPROVAL_INFO VALUES (4, NOW(), NOW(), 4, 1, 1);
INSERT INTO APPROVAL_INFO VALUES (5, NOW(), NOW(), 5, 1, 0);
INSERT INTO APPROVAL_INFO VALUES (6, NOW(), NOW(), 6, 1, 1);
INSERT INTO APPROVAL_INFO VALUES (7, NOW(), NOW(), 7, 0, 0);
INSERT INTO APPROVAL_INFO VALUES (8, NOW(), NOW(), 8, 1, 0);
INSERT INTO APPROVAL_INFO VALUES (9, NOW(), NOW(), 9, 1, 1);

-- =========================================================
-- CERTIFICATE GENERATION
-- =========================================================
INSERT INTO CERTIFICATE_INFO VALUES (1, NOW(), NOW(), 2, "https://drive.google.com/od-form-certificate");
INSERT INTO CERTIFICATE_INFO VALUES (2, NOW(), NOW(), 3, "https://drive.google.com/internship-permission-certificate");
INSERT INTO CERTIFICATE_INFO VALUES (3, NOW(), NOW(), 4, "https://drive.google.com/project-extension-certificate");
INSERT INTO CERTIFICATE_INFO VALUES (4, NOW(), NOW(), 11, "https://drive.google.com/medical-leave-certificate");
INSERT INTO CERTIFICATE_INFO VALUES (5, NOW(), NOW(), 12, "https://drive.google.com/internship-approval-certificate");
INSERT INTO CERTIFICATE_INFO VALUES (6, NOW(), NOW(), 13, "https://drive.google.com/project-approval-certificate");
